# Generated by Django 4.0 on 2025-01-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=150)),
                ('bankdetails', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='suspended_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('dt', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('bankid', models.IntegerField()),
                ('accno', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('type_of_acc', models.CharField(max_length=50)),
                ('dt', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
                ('addr1', models.CharField(max_length=500)),
                ('addr2', models.CharField(max_length=500)),
                ('addr3', models.CharField(max_length=500)),
                ('pin', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_bank_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('bankid', models.IntegerField()),
                ('t_no', models.CharField(max_length=50)),
                ('t_type', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('dt', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_bank_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_userid', models.IntegerField()),
                ('to_userid', models.IntegerField()),
                ('t_no', models.CharField(max_length=50)),
                ('t_type', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('dt', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
