# Generated by Django 4.0 on 2025-01-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bank_master_suspended_accounts_user_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_master',
            old_name='bankdetails',
            new_name='bankaddress',
        ),
        migrations.AddField(
            model_name='bank_master',
            name='bankcontact',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank_master',
            name='bankemail',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank_master',
            name='bankifsc',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
